## **read_data**

In [ ]:
import pandas as pd

apartment_df = pd.read_csv('.\\train.csv')
apartment_df.head()

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
0,0,7622,서울특별시,신교동,6-13,신현(101동),신교동 6-13 신현(101동),84.82,2002,200801,21~31,2,37500
1,1,5399,서울특별시,필운동,142,사직파크맨션,필운동 142 사직파크맨션,99.17,1973,200801,1~10,6,20000
2,2,3578,서울특별시,필운동,174-1,두레엘리시안,필운동 174-1 두레엘리시안,84.74,2007,200801,1~10,6,38500
3,3,10957,서울특별시,내수동,95,파크팰리스,내수동 95 파크팰리스,146.39,2003,200801,11~20,15,118000
4,4,10639,서울특별시,내수동,110-15,킹스매너,내수동 110-15 킹스매너,194.43,2004,200801,21~31,3,120000

In [ ]:
park_df = pd.read_csv('.\\park.csv')
park_df.head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
0,부산광역시,남구,대연동,대연공원,근린공원,55227.0,NaN,NaN,NaN,NaN,NaN,1944.0,2018-08-14
1,부산광역시,남구,대연동,당곡공원,역사공원,75465.0,NaN,NaN,NaN,NaN,NaN,1944.0,2018-08-14
2,부산광역시,남구,대연동,대일어린이공원,어린이공원,422.1,NaN,NaN,NaN,NaN,NaN,1965.0,2018-08-14
3,부산광역시,남구,대연동,못골어린이공원,어린이공원,499.8,NaN,NaN,NaN,NaN,NaN,1968.0,2018-08-14
4,부산광역시,남구,용호동,솔밭어린이공원,어린이공원,1500.2,NaN,NaN,NaN,NaN,NaN,1970.0,2018-08-14

In [ ]:
day_care_center_df = pd.read_csv('.\\day_care_center.csv')
day_care_center_df.head()

,city,gu,day_care_name,day_care_type,day_care_baby_num,teacher_num,nursing_room_num,playground_num,CCTV_num,is_commuting_vehicle,reference_date
0,서울특별시,서대문구,가람어린이집,국공립,70,11.0,5.0,1.0,7.0,N,2018-07-31
1,서울특별시,서대문구,가좌제일어린이집,국공립,88,22.0,5.0,2.0,10.0,N,2018-07-31
2,서울특별시,서대문구,경찰청어린이집,직장,90,23.0,6.0,1.0,32.0,N,2018-07-31
3,서울특별시,서대문구,고운햇살어린이집,가정,18,5.0,3.0,0.0,4.0,N,2018-07-31
4,서울특별시,서대문구,고은어린이집,국공립,93,20.0,7.0,2.0,10.0,N,2018-07-31

In [ ]:
# 결측치 없음!
apartment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1216553 entries, 0 to 1216552
Data columns (total 13 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1216553 non-null  int64
 1   apartment_id            1216553 non-null  int64
 2   city                    1216553 non-null  object
 3   dong                    1216553 non-null  object
 4   jibun                   1216553 non-null  object
 5   apt                     1216553 non-null  object
 6   addr_kr                 1216553 non-null  object
 7   exclusive_use_area      1216553 non-null  float64
 8   year_of_completion      1216553 non-null  int64
 9   transaction_year_month  1216553 non-null  int64
 10  transaction_date        1216553 non-null  object
 11  floor                   1216553 non-null  int64
 12  transaction_real_price  1216553 non-null  int64
dtypes: float64(1), int64(6), object(6)
memory usage: 120.7+ MB

In [13]:
import numpy as np

np.unique(apartment_df['city'])

array(['부산광역시', '서울특별시'], dtype=object)

In [ ]:
# 200801부터 201711까지 데이터 
np.sort(np.unique(apartment_df['transaction_year_month']))

array([200801, 200802, 200803, 200804, 200805, 200806, 200807, 200808,
       200809, 200810, 200811, 200812, 200901, 200902, 200903, 200904,
       200905, 200906, 200907, 200908, 200909, 200910, 200911, 200912,
       201001, 201002, 201003, 201004, 201005, 201006, 201007, 201008,
       201009, 201010, 201011, 201012, 201101, 201102, 201103, 201104,
       201105, 201106, 201107, 201108, 201109, 201110, 201111, 201112,
       201201, 201202, 201203, 201204, 201205, 201206, 201207, 201208,
       201209, 201210, 201211, 201212, 201301, 201302, 201303, 201304,
       201305, 201306, 201307, 201308, 201309, 201310, 201311, 201312,
       201401, 201402, 201403, 201404, 201405, 201406, 201407, 201408,
       201409, 201410, 201411, 201412, 201501, 201502, 201503, 201504,
       201505, 201506, 201507, 201508, 201509, 201510, 201511, 201512,
       201601, 201602, 201603, 201604, 201605, 201606, 201607, 201608,
       201609, 201610, 201611, 201612, 201701, 201702, 201703, 201704,
       201705, 201706, 201707, 201708, 201709, 201710, 201711],
      dtype=int64)

In [15]:
np.sort(np.unique(apartment_df['year_of_completion']))

array([1961, 1962, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973,
       1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984,
       1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995,
       1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017],
      dtype=int64)

In [ ]:
# 1961년에 지어진 아파트
apartment_df[apartment_df['year_of_completion'] == 1961].head()

,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
376092,376092,82,서울특별시,구로동,718-18,(718-18)삼성빌라트,구로동 718-18 (718-18)삼성빌라트,54.16,1961,200802,11~20,5,12000
376142,376142,9108,서울특별시,구로동,748-24,은진빌라(748-24),구로동 748-24 은진빌라(748-24),59.92,1961,200802,21~29,1,14000
376389,376389,82,서울특별시,구로동,718-18,(718-18)삼성빌라트,구로동 718-18 (718-18)삼성빌라트,44.55,1961,200803,1~10,2,10000
376601,376601,241,서울특별시,구로동,780-86,(780-86),구로동 780-86 (780-86),35.55,1961,200803,21~31,1,8700
378005,378005,277,서울특별시,구로동,794-26,(794-26),구로동 794-26 (794-26),48.13,1961,200806,11~20,4,16000

In [ ]:
# 결측치 다수 존재
park_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   city                         1359 non-null   object
 1   gu                           1356 non-null   object
 2   dong                         1359 non-null   object
 3   park_name                    1359 non-null   object
 4   park_type                    1359 non-null   object
 5   park_area                    1359 non-null   float64
 6   park_exercise_facility       277 non-null    object
 7   park_entertainment_facility  435 non-null    object
 8   park_benefit_facility        266 non-null    object
 9   park_cultural_facitiy        72 non-null     object
 10  park_facility_other          175 non-null    object
 11  park_open_year               937 non-null    float64
 12  reference_date               1359 non-null   object
dtypes: float64(2), object(11)
memory usage: 138.2+ KB

In [19]:
np.unique(park_df['city'])

array(['부산광역시', '서울특별시'], dtype=object)

In [ ]:
# 결측치가 아닌 데이터만 추출
park_df[park_df['park_exercise_facility'].notna()].head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
50,부산광역시,연제구,연산동,과정공원,어린이공원,1946.5,게이트볼장,조합놀이대 등,화장실,NaN,파고라 및 체력단련시설 등,1973.0,2018-04-04
55,부산광역시,연제구,거제동,거제체육공원,체육공원,5848.5,게이트볼장,NaN,NaN,NaN,파고라 및 체력단련시설 등,2003.0,2018-04-04
169,부산광역시,부산진구,개금동,개금테마공원,근린공원,28881.0,풋살운동장,"""조합놀이대, 그네, 시소""",화장실,NaN,NaN,1986.0,2018-04-05
181,부산광역시,부산진구,당감동,미리내어린이공원,어린이공원,2969.2,배드민턴장,"""시소, 흔들놀이기구""",NaN,NaN,NaN,1994.0,2018-04-05
195,서울특별시,양천구,신정동,신정3동소공원,소공원,3353.0,야외헬스형운동기구 1개,NaN,NaN,NaN,NaN,2012.0,2018-07-31

In [22]:
# 결측치인 데이터만 추출
park_df[park_df['park_exercise_facility'].isna()].head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
0,부산광역시,남구,대연동,대연공원,근린공원,55227.0,NaN,NaN,NaN,NaN,NaN,1944.0,2018-08-14
1,부산광역시,남구,대연동,당곡공원,역사공원,75465.0,NaN,NaN,NaN,NaN,NaN,1944.0,2018-08-14
2,부산광역시,남구,대연동,대일어린이공원,어린이공원,422.1,NaN,NaN,NaN,NaN,NaN,1965.0,2018-08-14
3,부산광역시,남구,대연동,못골어린이공원,어린이공원,499.8,NaN,NaN,NaN,NaN,NaN,1968.0,2018-08-14
4,부산광역시,남구,용호동,솔밭어린이공원,어린이공원,1500.2,NaN,NaN,NaN,NaN,NaN,1970.0,2018-08-14

In [ ]:
# NaN 값이 포함되어 있기때문에 .str 사용불가 (NaN은 float 자료형)
park_df[park_df['park_exercise_facility'].str.contains('게이트볼장')]

ValueError: Cannot mask with non-boolean array containing NA / NaN values

In [28]:
type(park_df['park_exercise_facility'].astype(str)[0])

str

In [29]:
type(park_df['park_exercise_facility'][0])

float

In [ ]:
# 이처럼 결측치가 존재하는 컬럼은 데이터타입을 str로 바꾸어 사용
# NaN -> 'NaN' 으로 바뀜 (문자열로)
park_df[park_df['park_exercise_facility'].astype(str).str.contains('게이트볼장')].head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
50,부산광역시,연제구,연산동,과정공원,어린이공원,1946.5,게이트볼장,조합놀이대 등,화장실,NaN,파고라 및 체력단련시설 등,1973.0,2018-04-04
55,부산광역시,연제구,거제동,거제체육공원,체육공원,5848.5,게이트볼장,NaN,NaN,NaN,파고라 및 체력단련시설 등,2003.0,2018-04-04
272,서울특별시,금천구,독산동,감로천생태공원,근린공원,15000.0,"""배드민턴장, 게이트볼장""",NaN,NaN,NaN,CCTV,1968.0,2018-08-19
290,서울특별시,중구,만리동2가,손기정공원,체육공원,29682.0,"""축구장, 게이트볼장, 테니스장""",조합놀이대,"""화장실,주차장""",NaN,NaN,1987.0,2018-05-21
390,서울특별시,동대문구,장안동,장안,근린공원,14744.8,"""배드민턴장, 족구장, 게이트볼장, 농구장 반코트""","""조합놀이대, 그네""","""정자, 벤치, 화장실""",독서실,"""바닥분수, 계류""",1988.0,2018-03-31

In [ ]:
park_df.sort_values('park_area', ascending=False).head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
894,서울특별시,노원구,상계동,수락산공원,도시농업공원,6692795.0,NaN,NaN,NaN,NaN,등산로 및 각종시설,NaN,2019-01-29
895,서울특별시,노원구,중계동,불암산공원,도시농업공원,5334267.0,NaN,NaN,NaN,NaN,등산로 및 각종시설,NaN,2019-01-29
565,부산광역시,NaN,영주동,중앙공원,근린공원,5020657.0,"""운동광장, 게이트볼, 궁도장, 구민운동장, 풋살경기장, 다목적 마당, 인라인스케이...","""어린이놀이터, 발물놀이터""","""주차장,화장실, 대중음식점,매점,전망대,다과점,치유센터,숲속요가장및 풍욕장, 낙상...","""도서관, 기념비, 충혼탑, 장건상동상, 대한해협전승비, 자연보호헌장, 시민헌장, ...","""도로, 광장, 파고라, 못, 생태연못, 야영장, 음수대, 휴게소, 야유회장, 전망...",1986.0,2018-08-01
167,부산광역시,부산진구,초읍동,어린이대공원,근린공원,4947290.0,NaN,NaN,NaN,NaN,NaN,1978.0,2018-04-05
566,부산광역시,NaN,초읍동,어린이대공원,근린공원,4947290.0,"""골프연습장, 배드민턴장""","""케이블카, 어린이유희시설, 가족유희시설, 짚라인""","""제1주차장, 전망대, 매점, 매점(기념품), 휴게음식점, 간이화장실, 공중화장실...","""동물원시설, 어린이회관, 학생수련회야영장, 반공전시관, 전시관, 위인탑, 교육문화...","""경로당, 야영장, 힐링데크, 트리하우스, 스카이워크, 산림욕장, 관리사무소, 안내...",1978.0,2018-08-01

In [31]:
park_df.sort_values(['park_area', 'park_open_year'], ascending=[True, False]).head()

,city,gu,dong,park_name,park_type,park_area,park_exercise_facility,park_entertainment_facility,park_benefit_facility,park_cultural_facitiy,park_facility_other,park_open_year,reference_date
1281,부산광역시,수영구,광안동,광안1동 소공원,소공원,22.0,NaN,NaN,NaN,NaN,NaN,2013.0,2018-09-01
642,서울특별시,은평구,녹번동,도원극장옆마을마당,기타,48.8,NaN,NaN,NaN,NaN,NaN,NaN,2018-02-14
1077,서울특별시,강남구,도곡동,도곡동 426-9(로덴하우스)소공원,소공원,80.0,NaN,NaN,NaN,NaN,NaN,NaN,2018-08-27
960,서울특별시,광진구,구의동,구의가로휴식공원,소공원,95.2,NaN,NaN,NaN,NaN,NaN,1971.0,2019-02-26
792,서울특별시,송파구,마천동,돌무데기,어린이공원,97.6,NaN,NaN,NaN,NaN,NaN,NaN,2019-01-01

In [33]:
park_df.pivot_table(index=['city', 'gu', 'dong'], values='park_area', aggfunc=['sum', 'count']).sort_values([('count', 'park_area'), ('sum', 'park_area')], ascending=False).head(20)

                      sum     count
                park_area park_area
city  gu  dong
서울특별시 강서구 화곡동   1410219.8        31
부산광역시 강서구 명지동    348482.8        25
서울특별시 강서구 방화동    313348.3        25
      서초구 양재동    454614.0        21
      송파구 문정동    232695.0        20
부산광역시 북구  화명동    171462.4        20
서울특별시 송파구 마천동    324979.2        19
      서초구 방배동    328598.7        18
      강남구 역삼동     55135.6        18
부산광역시 북구  만덕동    407124.7        17
서울특별시 서초구 반포동     90820.9        17
부산광역시 연제구 연산동     44453.2        17
서울특별시 강남구 개포동    422235.9        16
      서초구 우면동    167527.5        16
      강서구 등촌동     48255.2        16
      동작구 사당동   1154163.6        15
      서초구 서초동    570928.3        15
부산광역시 남구  대연동    411583.1        15
서울특별시 송파구 거여동    282991.6        15
부산광역시 동래구 온천동   3249492.7        14

In [34]:
day_care_center_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7551 entries, 0 to 7550
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   city                  7551 non-null   object
 1   gu                    7551 non-null   object
 2   day_care_name         7551 non-null   object
 3   day_care_type         7551 non-null   object
 4   day_care_baby_num     7551 non-null   int64
 5   teacher_num           7326 non-null   float64
 6   nursing_room_num      4352 non-null   float64
 7   playground_num        3626 non-null   float64
 8   CCTV_num              5280 non-null   float64
 9   is_commuting_vehicle  7055 non-null   object
 10  reference_date        7551 non-null   object
dtypes: float64(4), int64(1), object(6)
memory usage: 649.0+ KB

In [35]:
np.unique(day_care_center_df['city'])

array(['부산광역시', '서울특별시'], dtype=object)

In [37]:
day_care_center_df.sort_values(['day_care_baby_num', 'teacher_num'], ascending=[False, True]).head()

,city,gu,day_care_name,day_care_type,day_care_baby_num,teacher_num,nursing_room_num,playground_num,CCTV_num,is_commuting_vehicle,reference_date
4028,부산광역시,북구,숲속은성어린이집,민간,489,49.0,19.0,0.0,24.0,Y,2018-10-18
3589,부산광역시,동래구,혜화어린이집,민간,300,33.0,18.0,1.0,20.0,Y,2018-07-09
6036,부산광역시,강서구,무궁화어린이집,사회복지법인,300,34.0,15.0,0.0,25.0,Y,2018-10-31
577,서울특별시,송파구,서울아산병원어린이집,직장,300,49.0,NaN,NaN,26.0,N,2018-08-03
1339,서울특별시,서초구,삼성전자서울R&D캠퍼스어린이집,직장,300,50.0,NaN,NaN,NaN,N,2018-07-25

In [39]:
day_care_center_df.pivot_table(index=['city', 'gu'], values=['day_care_baby_num', 'teacher_num'], aggfunc=['sum', 'count', 'mean', 'median']).sort_values(('sum', 'day_care_baby_num'), ascending=False).head(10)

                         sum                         count              \
           day_care_baby_num teacher_num day_care_baby_num teacher_num
city  gu
서울특별시 강서구              35150      7032.0               874         874
      송파구              16846      3561.0               409         409
      은평구              14011      2615.0               283         283
      노원구              13711      3235.0               457         455
      구로구              13466      2797.0               334         334
      강동구              13278      2690.0               272         272
      양천구              12460      2541.0               316         316
      영등포구             12005      2459.0               266         266
      강남구              11605         0.0               223           0
      관악구              11543      2463.0               271         271

                        mean                        median
           day_care_baby_num teacher_num day_care_baby_num teacher_num
city  gu
서울특별시 강서구          40.217391    8.045767              20.0         7.0
      송파구          41.188264    8.706601              23.0         7.0
      은평구          49.508834    9.240283              40.0         8.0
      노원구          30.002188    7.109890              19.0         6.0
      구로구          40.317365    8.374251              20.0         7.0
      강동구          48.816176    9.889706              32.0         8.0
      양천구          39.430380    8.041139              20.0         6.0
      영등포구         45.131579    9.244361              28.5         7.0
      강남구          52.040359         NaN              45.0         NaN
      관악구          42.594096    9.088561              28.0         8.0

In [40]:
np.unique(day_care_center_df['day_care_type'])

array(['가정', '국공립', '민간', '법인·단체', '사회복지법인', '직장', '협동'], dtype=object)

In [ ]:
# 부산, 서울 데이터 나눠서 저장하기
import os

def split_by_city(df, file_name) : 
    cities = np.unique(df['city'])
    for city in cities:
        if city not in os.listdir('data'): 
            os.mkdir(f'.\\data\\{city}')
        df[df['city'] == city].to_csv(f'.\\data\\{city}\\{file_name}.csv')

In [ ]:
location_df = pd.read_csv('.\\동별좌표.csv')

In [50]:
split_by_city(location_df, "location_df")

In [51]:
split_by_city(apartment_df, 'apartment_df')
split_by_city(day_care_center_df, 'day_care_center_df')
split_by_city(park_df, 'park_df')

In [53]:
pd.read_csv('.\\data\\서울특별시\\apartment_df.csv').head()

,Unnamed: 0,transaction_id,apartment_id,city,dong,jibun,apt,addr_kr,exclusive_use_area,year_of_completion,transaction_year_month,transaction_date,floor,transaction_real_price
0,0,0,7622,서울특별시,신교동,6-13,신현(101동),신교동 6-13 신현(101동),84.82,2002,200801,21~31,2,37500
1,1,1,5399,서울특별시,필운동,142,사직파크맨션,필운동 142 사직파크맨션,99.17,1973,200801,1~10,6,20000
2,2,2,3578,서울특별시,필운동,174-1,두레엘리시안,필운동 174-1 두레엘리시안,84.74,2007,200801,1~10,6,38500
3,3,3,10957,서울특별시,내수동,95,파크팰리스,내수동 95 파크팰리스,146.39,2003,200801,11~20,15,118000
4,4,4,10639,서울특별시,내수동,110-15,킹스매너,내수동 110-15 킹스매너,194.43,2004,200801,21~31,3,120000